### ISSUE TITLE
rufus写不了。就光引导区了，UItraISO倒是可以

### ISSUE THREAD

**Issue by HA-JD** [taielab/Taie-RedTeam-OS#2]

**Comment by taielab** [comment]
UItraISO写镜像之后，能安装成功吗

**Comment by HA-JD** [comment]
????你这

**Comment by taielab** [comment]
实体机我自己测试不多，大多数是在虚拟机下进行iso镜像读取安装，实体机当时用的这个工具https://www.balena.io/etcher/

**Comment by HA-JD** [comment]
测试了可以用但是无法安装。

**Comment by HA-JD** [comment]
就是临时系统

**Comment by HA-JD** [comment]
安装不了啊，没有安装选项。

**Comment by HA-JD** [comment]
虚拟机也安装不了，就直接读取iso的没有安装到VMware

**Comment by taielab** [comment]
安装是在开机启动选择第三个选项 direct install 选项 或者
进入live模式后点击左上角的图标之后输入关键字install 关键字就会出现安装按钮 
点击即可在live模式安装到实体机

**Comment by HA-JD** [comment]
没见到这界面。开机就tab键
