### ISSUE TITLE
新版信息收集里面没工具

### ISSUE THREAD

**Issue by YW5zZWM** [taielab/Taie-RedTeam-OS#3]
新版信息收集里面没工具

**Comment by taielab** [comment]
我这边让人安装测试了一下是信息收集模块工具是有的

**Comment by YW5zZWM** [comment]
![捕获](https://user-images.githubusercontent.com/14837295/84368342-03b30080-ac08-11ea-8d11-02b17bcd942e.PNG)

**Comment by taielab** [comment]
信息收集模块主要在自动化套件那 单兵的只是一些补充
