### ISSUE TITLE
sourceforge与国内云盘都没看到有iso文件可以下载？

### ISSUE THREAD

**Issue by chenbihao** [taielab/Taie-RedTeam-OS#8]
Taie-RedTeam-OS-V2020.1.iso.md5
Taie-RedTeam-OS-V2020.1.iso.sha256

只有这2个文件，没有iso文件

**Comment by vipgoat** [comment]
是的，我前几天下载，都有。能下载。现在没有ISO 的文件下载

**Comment by taielab** [comment]
链接: https://pan.baidu.com/s/1FAo4tSf2d0cQrp1P_X74eg 密码: mdgs
