### ISSUE TITLE
直接使用root用户登录会报错

### ISSUE THREAD

**Issue by xsshim** [taielab/Taie-RedTeam-OS#9]
![图片](https://user-images.githubusercontent.com/24834308/85000591-353a4780-b185-11ea-97cc-7abf7f028160.png)
![图片](https://user-images.githubusercontent.com/24834308/85000618-3f5c4600-b185-11ea-9cb2-8a9048234b93.png)
直接使用root用户登录会报错

**Comment by taielab** [comment]
制作系统的时候未基于root用户模式进行，所以所有环境都在非root下生效。建议勿用root作为正常使用
